### ISSUE TITLE
No valid accounts with access to the file/folder. Exiting...

### ISSUE THREAD

**Issue by murdock-commits** [architdate/drivedl#1]
Tried a lot of times. Everything's in place but still doesn't work, was this working earlier ?

**Input**: `python drivedl folderid location`

**Output:** `No valid accounts with access to the file/folder. Exiting...`

Drive API for Python is installed; Credentials are in place; All the dependencies are also installed.

I'm running drivedl from `$HOME/.local/lib/python3.6/site-packages/drivedl`

On running `python drivedl.py` I get `Usage: tdlist <folderid> <destination>`
 
TRIED THIS ALREADY:
- [x] Recreating credentials.json

- [x] Reinstalling drivedl

**EDIT:** Formatting.

**Comment by architdate** [comment]
You need to add an account first, try `$ python drivedl.py --add`
Let me know if that lets you add an account

**Comment by murdock-commits** [comment]
It works now. Thank you.
TBH the wiki is not well-written. It took me a lot of time and brainstorming to set this up. Although it appears to be a simple application; setting it up is not as simple as it looks. You might wanna spend some time on the wiki.

**Comment by murdock-commits** [comment]
BTW I'm getting this error while choosing to download folders.
```
Traceback (most recent call last):
  File "drivedl.py", line 195, in <module>
    main(False)
  File "drivedl.py", line 175, in main
    p = Pool(PROCESS_COUNT)
UnboundLocalError: local variable 'PROCESS_COUNT' referenced before assignment
```

**Comment by architdate** [comment]
Latest commit already fixes that. Update via pip (`pip install -U drivedl`)

Regarding wiki, I'll add it when I have time this weekend
